### PR TITLE
add dart support

### PR DESCRIPTION
**Pull request by jsiedentop**
Based on the work of sachaarbonel I added the generation of the dart client.

I did not finish the publishing part in release.sh, because the ownership of the package should be at ory. The steps are documented at: https://dart.dev/tools/pub/publishing

### CODE REVIEW

**Comment by aeneasr** [comment]
Thank you for your effort! I will now look into dart publishing :)

**Comment by aeneasr** [comment]
Looks like it is not currently supported to publish dart packages as a CI task: https://github.com/dart-lang/pub/issues/2227

**Comment by aeneasr** [comment]
Ok, so I have published the raw packages now:

- https://pub.dev/packages/ory_kratos_client
- https://pub.dev/packages/ory_oathkeeper_client
- https://pub.dev/packages/ory_keto_client
- https://pub.dev/packages/ory_hydra_client

Apparently it is possible to run this in a CI. Will try to do that now.

**Comment by jsiedentop** [comment]
Awesome! That was quick 👍 I'm happy to use the official packages instead of the local build ones.

**Comment by aeneasr** [comment]
Awesome! I think this should work now as part of the CI. I will do a test run now!

**Comment by jsiedentop** [comment]
I created a [new issue](https://github.com/ory/sdk/issues/53), because the published client is invalid and differs from the client I generated locally.

**Pull request merged**
