### PR TITLE
chore: upgrade typescript client axios to version 1.6.2

### PR DESCRIPTION
**Pull request by amirzahavi**
## Related Issue or Design Document

#305 

## Checklist

- [x] I have read the [contributing guidelines](../blob/master/CONTRIBUTING.md) and signed the CLA.
- [x] I have referenced an issue containing the design document if my change introduces a new feature.
- [x] I have read the [security policy](../security/policy).
- [ ] I confirm that this pull request does not address a security vulnerability. 
      If this pull request addresses a security vulnerability, 
      I confirm that I got approval (please contact [security@ory.sh](mailto:security@ory.sh)) from the maintainers to push the changes.
- [ ] I have added tests that prove my fix is effective or that my feature works.
- [ ] I have added the necessary documentation within the code base (if appropriate).

### CODE REVIEW

**Comment by aeneasr** [comment]
Closing as per https://github.com/ory/sdk/pull/303#issuecomment-1812111204

**Comment by aeneasr** [comment]
Closing as per https://github.com/ory/sdk/pull/303#issuecomment-1812111204

**Comment by amirzahavi** [comment]
Hey @aeneasr,
I understand now that the code is auto-generated, unfortunately, the linked comment states that it will be done in a couple of days (Nov 2023), but the Axios dependency is still a very old version.

Thanks 🙏🏽

**Comment by Oscmage** [comment]
Hey @aeneasr 

To @amirzahavi point, from what I can see the client is still a two year old version of Axios(or am I missing something?):

https://github.com/ory/sdk/blob/master/clients/client/typescript/package-lock.json#L30-L31

It is difficult for us to motivate staying customers of Ory Network (which was primarily a move done for security purposes) if dependencies to client libraries are not maintained, especially when the dependencies have open security vulnerabilities.

Do you run vulnerability scanning on the SDKs that you mention on your [webpage](https://www.ory.sh/security/)?

**Comment by Oscmage** [comment]
In 1.5.2 version of the client it uses a new version of axios 🎉

**Pull request closed without merging**
