### PR TITLE
feat: add dotnet SDK generation

### PR DESCRIPTION
**Pull request by Marcuzz**
Started work on generating and pushing a dotnet package to NuGet.

This requires the `NUGET_API_KEY` environment variable to be set in CI as well as the `Ory` org to be claimed at NuGet.

Any guidance on how to test this implementation would be good, it should work right away but I haven't found a way to test it.

### CODE REVIEW

**Comment by aeneasr** [comment]
This looks great! I've set up a nuget account  and `ory` organization. Do I need to create the packages as well or does this happen automatically?

And sorry for the late response by the way!

**Comment by Marcuzz** [comment]
That's okay!

The package should be created automatically and I believe you need to create an API key with the following settings, here: https://www.nuget.org/account/apikeys

image

**Comment by aeneasr** [comment]
Cool, thank you for the great help! One question, is it more common to lowercase the org name or uppercase the first char in Nuget?

**Comment by aeneasr** [comment]
For both the organization and packages :)

**Comment by Marcuzz** [comment]
You're welcome 😄  

The convention is to use PascalCase so both the organization and package names should start with an uppercase character which means it should be something like `Ory.Hydra.Sdk` 😄

**Comment by aeneasr** [comment]
Awesome! So now the last thing is that I think you might have registered `Ory`? :) If it was you, could you delete it so that I can create an org with the correct naming convention? Thank you!

**Comment by Marcuzz** [comment]
Oh, I edited the page with `Inspect Element` to make it look like Ory, I definitely didn't create the organization 😅 

Ory doesn't exist currently, so I don't think it's registered: https://www.nuget.org/profiles/Ory

**Comment by aeneasr** [comment]
Hm, interesting, maybe it lowercases the identifiers. I'll try to figure it out. And also AAA+ for effort with code inspection :)

**Comment by aeneasr** [comment]
Shit, I registered the org `ory` and the name is now blocked. I assumed that I'd have to recreate it with uppercase, which well, apparently is not possible :D

**Comment by Marcuzz** [comment]
Uh oh, let's hope it's just cached and that it will be available again soon. I'd just give it a little while 😅

**Comment by aeneasr** [comment]
I fear not:

```
Hello,

Thank you for contacting NuGet support. Your account ‘ory’ was deleted.
The name 'ory' will be reserved, and cannot be re-used.

Best regards,
The NuGet Team
```

I'll probably just name the org `OrySDK` then. Would that also be PascalCase (abbreviations)? So `OrySdk`?

**Comment by aeneasr** [comment]
Wrote support a quick message, let's see if they can help.

**Comment by Marcuzz** [comment]
Yeah `OrySdk` should be fine if they can't help you get `Ory` back, the organization name doesn't matter too much as the package name can still be `Ory.Hydra.Sdk` even if the organization name is `OrySdk` 😄

**Comment by aeneasr** [comment]
Cool, thank you so much for your help! I will try to complete this today and then we'll hopefully be able to publish the dotnet SDKs :)

**Comment by aeneasr** [comment]
Ok awesome, so I signed up `ory-sdk` and set up the API keys to get this merged :)

**Comment by aeneasr** [comment]
Did a test release, looks like there's a directory missing: https://app.circleci.com/pipelines/github/ory/sdk/169/workflows/1849ffe3-e707-4b78-b3e9-c7ed8087b45e/jobs/169

Would you be open to investigate? :)

**Comment by Marcuzz** [comment]
Yeah, it looks like I wasn't supposed to use the git stuff, oops!

**Pull request merged**
