### PR TITLE
fix: icu-libs not found when running dotnet pack

### LINKED ISSUE #34: Dotnet SDK generation fails
```
+ dotnet pack
Process terminated. Couldn't find a valid ICU package installed on the system. Set the configuration flag System.Globalization.Invariant to true if you want to run with no globalization support.
   at System.Environment.FailFast(System.String)
   at System.Globalization.GlobalizationMode.GetGlobalizationInvariantMode()
   at System.Globalization.GlobalizationMode..cctor()
   at System.Globalization.CultureData.CreateCultureWithInvariantData()
   at System.Globalization.CultureData.get_Invariant()
   at System.Globalization.CultureInfo..cctor()
   at System.String.ToLowerInvariant()
   at Microsoft.DotNet.PlatformAbstractions.RuntimeEnvironment.GetArch()
   at Microsoft.DotNet.PlatformAbstractions.RuntimeEnvironment..cctor()
   at Microsoft.DotNet.PlatformAbstractions.RuntimeEnvironment.GetRuntimeIdentifier()
   at Microsoft.DotNet.Cli.MulticoreJitProfilePathCalculator.CalculateProfileRootPath()
   at Microsoft.DotNet.Cli.MulticoreJitActivator.StartCliProfileOptimization()
   at Microsoft.DotNet.Cli.MulticoreJitActivator.TryActivateMulticoreJit()
   at Microsoft.DotNet.Cli.Program.Main(System.String[])
./scripts/release.sh: line 109:  4253 Aborted                 (core dumped) dotnet pack
```

See https://app.circleci.com/pipelines/github/ory/sdk/181/workflows/688e5aae-2b58-41d1-a6c0-e4deb95a6299/jobs/180

/cc @Marcuzz

### PR DESCRIPTION
**Pull request by Marcuzz**
This should fix #34

I'm excited to see what the next error will be 😅

### CODE REVIEW

**Comment by zepatrik** [comment]
Is there no way to test it outside of our CI build?

**Comment by Marcuzz** [comment]
Yeah, it's a bit tricky but I'll do some testing. Please don't merge this yet 🙂

**Comment by Marcuzz** [comment]
@zepatrik @aeneasr I have now tested it fully and am confident this PR fixes packing and building of the dotnet SDK.

The models unfortunately had to be prefixed with the project name as Keto's `Version` model's name is ambiguous with `System.Version` (OpenAPI generator doesn't use fully qualified names for the csharp-netcore generator)

**Comment by aeneasr** [comment]
Thank you, @Marcuzz !

> Is there no way to test it outside of our CI build?

It's quite difficult because you need to customize the scripts a lot. E.g. disable publish on maven, npm etc and then also set up a working dotnet publish pipeline :/

**Comment by aeneasr** [comment]
😎 😎 😎 😎 

Bildschirmfoto 2020-09-06 um 08 59 13

**Pull request merged**
