### PR TITLE
fix: UiNodeAttributes enum with serde untagged

### PR DESCRIPTION
**Pull request by extraymond**
## Checklist

- [v] I have read the [contributing guidelines](../blob/master/CONTRIBUTING.md)
      and signed the CLA.
- [v] I have read the [security policy](../security/policy).
- [ ] I confirm that this pull request does not address a security
      vulnerability. If this pull request addresses a security vulnerability, I
      confirm that I got green light (please contact
      [security@ory.sh](mailto:security@ory.sh)) from the maintainers to push
      the changes.
- [ ] I have added tests that prove my fix is effective or that my feature
      works.
- [ ] I have added necessary documentation within the code base (if
      appropriate).

## Further comments

For all the six oneOf usage in the openapi spec, 5 out of 6 rust model generated by the openapi-generator did produce a enum correctly.

However the UiNodeAttributes object was wrongly mapped to a combined struct instead of a enum of the 4 possible variant.
This pr hand the specific struct and replace it with a untagged enum. So when deserializing, serde should be able to try all the variant and find the correctly mapped one.

Since the Self::new method is not used directly, deprecating it might be ok. Client might not need to create this object but expect to receive it from the http.response.

### CODE REVIEW

**Comment by aeneasr** [comment]
Thank you! Unfortunately, this change would immediately be overwritten by the next release by the autogenerator. We need to find another way to resolve this :(

**Comment by extraymond** [comment]
I see, did including a patched_file and override the generated one within the build script enough?

**Comment by aeneasr** [comment]
As per comment https://github.com/ory/sdk/issues/72#issuecomment-883215804 I think it would be great if we could find something that fixes the issue - you said that other structs are generated fine - maybe we can replicate that somehow? Or we can figure out why others work while this isn't?

**Comment by aeneasr** [comment]
Overrides are difficult because we have to maintain them, and we do not have Rust experience in Ory at the moment.

**Comment by aeneasr** [comment]
I will close this PR in the meanwhile because we can not merge it as is :/ But thank you for the contribution, I hope that we can find another way to fix the issue!

**Comment by extraymond** [comment]
No problem! Looking forward to help solving this. Thanks for the work for maintaining a fairly extensive sdk across langaues!!!

**Pull request closed without merging**
