### PR TITLE
chore: add ci for pr

### PR DESCRIPTION
**Pull request by jonas-jonas**
## Checklist

- [ ] I have read the [contributing guidelines](../blob/master/CONTRIBUTING.md) and signed the CLA.
- [ ] I have referenced an issue containing the design document if my change introduces a new feature.
- [ ] I have read the [security policy](../security/policy).
- [ ] I confirm that this pull request does not address a security vulnerability. 
      If this pull request addresses a security vulnerability, 
      I confirm that I got approval (please contact [security@ory.sh](mailto:security@ory.sh)) from the maintainers to push the changes.
- [ ] I have added tests that prove my fix is effective or that my feature works.
- [ ] I have added the necessary documentation within the code base (if appropriate).

### CODE REVIEW

**Comment by aeneasr** [comment]
The generate script needs a specific commit message to execute. Could we somehow change this to just execute the script on the latest file available? Check the README for extra options :)

**Comment by jonas-jonas** [comment]
Sure thing, I'll see what we can do here, first I wanted to get the CI running at all, can you give me permission to push to the repo directly?

**Comment by aeneasr** [comment]
dones

**Comment by jonas-jonas** [comment]
Replaced by branch & pr on origin

**Pull request closed without merging**
