### PR TITLE
WIP Dart SDK generation

### PR DESCRIPTION
**Pull request by sachaarbonel**
Progess for #27 
I was about to edit the Dockerfile when I saw this [issue](https://github.com/dart-lang/dart_docker/issues/50). Apparently there are some problems with alpine due to `musl-libc`. Should I pursue it any way ?
In debian installing the sdk would be : 
```bash
 sudo apt-get update
 sudo apt-get install apt-transport-https
 sudo sh -c 'wget -qO- https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add -'
 sudo sh -c 'wget -qO- https://storage.googleapis.com/download.dartlang.org/linux/debian/dart_stable.list > /etc/apt/sources.list.d/dart_stable.list'
```
Also, I'm not sure what the equivalent of  `apt-key add -`would be, `gpg --import -`?

### CODE REVIEW

**Comment by aeneasr** [comment]
Yeah you can update the docker image to use debian if you want! We don't need to use alpine!

**Comment by aeneasr** [comment]
Are you still up for the changes? :)

**Comment by tacurran** [comment]
@sachaarbonel  Hi Sacha, can I help you finish this up? We would like to have Dart finished up.

**Comment by sachaarbonel** [comment]
Hi @tacurran yes feel free to take over I don't have a lot of free time lately. Thank's

**Comment by aeneasr** [comment]
Dart support is now merged! They are published


- https://pub.dev/packages/ory_kratos_client
- https://pub.dev/packages/ory_oathkeeper_client
- https://pub.dev/packages/ory_keto_client
- https://pub.dev/packages/ory_hydra_client

**Pull request closed without merging**
