### PR TITLE
Add Rust SDK

### PR DESCRIPTION
**Pull request by mojotalantikite**
This adds generation of a Rust SDK (#47), in case that's a thing people end up wanting. 

I did a quick test using the locally generated SDK and it seems to be working fine:

```rust
use ory_kratos_client::apis::{configuration, version_api};

#[tokio::main]
async fn main() {
    let base_path = "http://127.0.0.1:4433".to_owned();
    let config = configuration::Configuration {
        base_path,
        ..Default::default()
    };

    let version = version_api::get_version(&config).await.unwrap();
    println!("Kratos {:?}", version);
}
```
```shell
❯ cargo run
   Compiling test-kratos v0.1.0 (/Users/mojo/scratch/test-kratos)
    Finished dev [unoptimized + debuginfo] target(s) in 2.85s
     Running `target/debug/test-kratos`
Kratos Version { version: Some("v0.5.5-alpha.1") }
```

I didn't include the publishing of the Rust crate, as I'm assuming that ORY will need to make an account and such ([docs here](https://doc.rust-lang.org/cargo/reference/publishing.html)). Though I'd be happy to help add the scripting to publish the crate if this ends up being a path ORY wants to take.

### CODE REVIEW

**Comment by aeneasr** [comment]
Thank you! I'll look into crates this week!

**Comment by aeneasr** [comment]
Quick question, why did you choose reqwest over hyper? Asking out of curiosity :)

**Comment by aeneasr** [comment]
Ah I see, looks like async is only possible for reqwest

**Comment by mojotalantikite** [comment]
Yeah exactly, for async support. reqwest is also a bit higher level -- it's actually built on top of hyper. Thanks for getting this pulled in!

**Pull request merged**
