### PR TITLE
WIP on csharp SDK generation

### PR DESCRIPTION
**Pull request by alampros**
See ory/hydra#2017

I'm not real clear on how these scripts are actually executed, so I haven't tested this at all. I would have expected the built docker container to execute the `init.sh` etc, but I couldn't find how it does it.

I have no experience publishing to nuget, but in theory we should be able to use the `nuget.exe` that the generator emits to do the actual publishing.

Any help would be greatly appreciated!

### CODE REVIEW

**Comment by aeneasr** [comment]
This looks pretty solid to me already! I think it would make sense to publish this to nuget somehow. Do you know a good guide for this?

**Comment by Marcuzz** [comment]
It's probably advisable to use the csharp-netcore generator instead of the csharp generator because that will generate a .NET standard library compatible with both .NET Core and .NET Framework.

OpenAPI will generate the package metadata for you, here's a tutorial on how to submit the library to NuGet: https://docs.microsoft.com/en-us/nuget/quickstart/create-and-publish-a-package-using-the-dotnet-cli 😄

**Comment by aeneasr** [comment]
@Marcuzz would you be open to contributing that change? :)

**Comment by Marcuzz** [comment]
@aeneasr Yeah, I've made a new PR that should work #26

**Comment by aeneasr** [comment]
#26 is merged :)

**Pull request closed without merging**
