### PR TITLE
fix: enable discriminator lookup for java

### PR DESCRIPTION
**Pull request by WoodyWoodsta**
Adds discriminator lookups for Java `oneOf` specs. This fixes an issue where the `oneOf` specs weren't being automatically discriminated.

## Related Issue or Design Document
Fixes https://github.com/ory/kratos/issues/3807

## Checklist

- [ ] I have read the [contributing guidelines](../blob/master/CONTRIBUTING.md) and signed the CLA.
- [x] I have referenced an issue containing the design document if my change introduces a new feature.
- [x] I have read the [security policy](../security/policy).
- [x] I confirm that this pull request does not address a security vulnerability. 
      If this pull request addresses a security vulnerability, 
      I confirm that I got approval (please contact [security@ory.sh](mailto:security@ory.sh)) from the maintainers to push the changes.
- [ ] I have added tests that prove my fix is effective or that my feature works.
- [x] I have added the necessary documentation within the code base (if appropriate).

### CODE REVIEW

**Comment by aeneasr** [comment]
Awesome, nice find!

**Comment by WoodyWoodsta** [comment]
Thanks @aeneasr. What is the release schedule of the java sdk? (i.e. when can we expect this change to be published?)

**Comment by aeneasr** [comment]
The client SDK for Ory Network is released almost every time we release to Ory Network. For Ory OSS we release SDKs alongside releases for the projects

**Comment by WoodyWoodsta** [comment]
Even for an inop SDK? We'll have to sort out our own Maven repo or do something locally then :D

**Pull request merged**
